# EDA

In this EDA following questions are answered

* Dimensioner: hur många rader/kolumner?

* Datatyper: numeriska, kategoriska, datum, text?

* Vad representerar varje rad? (en kund, en transaktion, en dag?)

* Saknade värden (missing data) - hur mycket, och saknas det slumpmässigt eller systematiskt?

* Duplicerade rader

* Orimliga värden/outliers - negativa åldrar, orimliga datum, etc.

* Inkonsekvent formatering (t.ex. "USA", "usa", "United States" som samma sak)

* Numeriska: medelvärde, median, spridning (std/varians), min/max, distribution (histogram)

* Kategoriska: frekvenstabeller, hur många unika kategorier?

In [15]:
import pandas as pd
from backend.constants import DATA_PATH

## SOLAR DATASET

In [ ]:

solar_df = pd.read_csv(DATA_PATH/"solar.csv")

solar_df

In [17]:
solar_df.shape

(11898, 15)

In [40]:
solar_df.dtypes

Catalog Number         int64
Calendar Date            str
Eclipse Time             str
Delta T (s)            int64
Lunation Number        int64
Saros Number           int64
Eclipse Type             str
Gamma                float64
Eclipse Magnitude    float64
Latitude                 str
Longitude                str
Sun Altitude           int64
Sun Azimuth            int64
Path Width (km)          str
Central Duration         str
dtype: object

In [18]:
solar_df.info

<bound method DataFrame.info of        Catalog Number      Calendar Date Eclipse Time  Delta T (s)  \
0                   1      -1999 June 12     03:14:51        46438
1                   2   -1999 December 5     23:45:23        46426
2                   3       -1998 June 1     18:09:16        46415
3                   4  -1998 November 25     05:57:03        46403
4                   5     -1997 April 22     13:19:56        46393
...               ...                ...          ...          ...
11893           11894   2998 December 10     03:18:31         4414
11894           11895         2999 May 6     23:23:57         4417
11895           11896    2999 October 30     09:34:33         4420
11896           11897      3000 April 26     14:18:06         4424
11897           11898    3000 October 19     16:10:16         4428

       Lunation Number  Saros Number Eclipse Type   Gamma  Eclipse Magnitude  \
0               -49456             5            T -0.2701             1.0733
1               -49450            10            A -0.2317             0.9382
2               -49444            15            T  0.4994             1.0284
3               -49438            20            A -0.9045             0.9806
4               -49433           -13            P -1.4670             0.1611
...                ...           ...          ...     ...                ...
11893            12355           187            P  1.2838             0.4773
11894            12360           154            T  0.8388             1.0566
11895            12366           159           A- -1.0023             0.9586
11896            12372           164            T  0.1310             1.0222
11897            12378           169            H -0.2303             1.0049

      Latitude Longitude  Sun Altitude  Sun Azimuth Path Width (km)  \
0         6.0N     33.3W            74          344             247
1        32.9S     10.8E            76           21             236
2        46.2N     83.4E            60          151             111
3        67.8S    143.8W            25           74             162
4        60.6S    106.4W             0          281             NaN
...        ...       ...           ...          ...             ...
11893    67.2N    145.0E             0          179             NaN
11894    71.5N    177.3E            33          146             345
11895    70.9S     84.7W             0          137               -
11896    21.1N     18.4W            82          166              76
11897    23.1S     51.6W            77           16              17

      Central Duration
0               06m37s
1               06m44s
2               02m15s
3               01m14s
4                  NaN
...                ...
11893              NaN
11894           03m25s
11895                -
11896           02m11s
11897           00m29s

[11898 rows x 15 columns]>

In [19]:
solar_df.columns

Index(['Catalog Number', 'Calendar Date', 'Eclipse Time', 'Delta T (s)',
       'Lunation Number', 'Saros Number', 'Eclipse Type', 'Gamma',
       'Eclipse Magnitude', 'Latitude', 'Longitude', 'Sun Altitude',
       'Sun Azimuth', 'Path Width (km)', 'Central Duration'],
      dtype='str')

In [20]:
solar_df.head()

,Catalog Number,Calendar Date,Eclipse Time,Delta T (s),Lunation Number,Saros Number,Eclipse Type,Gamma,Eclipse Magnitude,Latitude,Longitude,Sun Altitude,Sun Azimuth,Path Width (km),Central Duration
0,1,-1999 June 12,03:14:51,46438,-49456,5,T,-0.2701,1.0733,6.0N,33.3W,74,344,247,06m37s
1,2,-1999 December 5,23:45:23,46426,-49450,10,A,-0.2317,0.9382,32.9S,10.8E,76,21,236,06m44s
2,3,-1998 June 1,18:09:16,46415,-49444,15,T,0.4994,1.0284,46.2N,83.4E,60,151,111,02m15s
3,4,-1998 November 25,05:57:03,46403,-49438,20,A,-0.9045,0.9806,67.8S,143.8W,25,74,162,01m14s
4,5,-1997 April 22,13:19:56,46393,-49433,-13,P,-1.4670,0.1611,60.6S,106.4W,0,281,NaN,NaN

In [21]:
solar_df.isna().sum()

Catalog Number          0
Calendar Date           0
Eclipse Time            0
Delta T (s)             0
Lunation Number         0
Saros Number            0
Eclipse Type            0
Gamma                   0
Eclipse Magnitude       0
Latitude                0
Longitude               0
Sun Altitude            0
Sun Azimuth             0
Path Width (km)      4200
Central Duration     4200
dtype: int64

In [28]:
solar_df.describe()

,Catalog Number,Delta T (s),Lunation Number,Saros Number,Gamma,Eclipse Magnitude,Sun Altitude,Sun Azimuth
count,11898.000000,11898.000000,11898.000000,11898.000000,11898.000000,11898.000000,11898.000000,11898.000000
mean,5949.500000,12142.172802,-18546.959321,87.483190,-0.002469,0.812748,36.505295,180.264330
std,3434.801086,13583.402888,17906.572982,48.380284,0.900860,0.300398,32.417350,110.745408
min,1.000000,-6.000000,-49456.000000,-13.000000,-1.569000,0.000000,0.000000,0.000000
25%,2975.250000,970.250000,-33954.750000,47.000000,-0.786575,0.675925,0.000000,89.000000
50%,5949.500000,5636.500000,-18495.000000,87.000000,-0.003850,0.950600,38.000000,180.000000
75%,8923.750000,20943.500000,-3039.250000,128.000000,0.776900,1.018400,66.000000,272.000000
max,11898.000000,46438.000000,12378.000000,190.000000,1.570600,1.081300,90.000000,360.000000

In [38]:
solar_df[solar_df.duplicated()]

Empty DataFrame
Columns: [Catalog Number, Calendar Date, Eclipse Time, Delta T (s), Lunation Number, Saros Number, Eclipse Type, Gamma, Eclipse Magnitude, Latitude, Longitude, Sun Altitude, Sun Azimuth, Path Width (km), Central Duration]
Index: []

## LUNAR DATASET

In [25]:

lunar_df = pd.read_csv(DATA_PATH/"solar.csv")

lunar_df

,Catalog Number,Calendar Date,Eclipse Time,Delta T (s),Lunation Number,Saros Number,Eclipse Type,Gamma,Eclipse Magnitude,Latitude,Longitude,Sun Altitude,Sun Azimuth,Path Width (km),Central Duration
0,1,-1999 June 12,03:14:51,46438,-49456,5,T,-0.2701,1.0733,6.0N,33.3W,74,344,247,06m37s
1,2,-1999 December 5,23:45:23,46426,-49450,10,A,-0.2317,0.9382,32.9S,10.8E,76,21,236,06m44s
2,3,-1998 June 1,18:09:16,46415,-49444,15,T,0.4994,1.0284,46.2N,83.4E,60,151,111,02m15s
3,4,-1998 November 25,05:57:03,46403,-49438,20,A,-0.9045,0.9806,67.8S,143.8W,25,74,162,01m14s
4,5,-1997 April 22,13:19:56,46393,-49433,-13,P,-1.4670,0.1611,60.6S,106.4W,0,281,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11893,11894,2998 December 10,03:18:31,4414,12355,187,P,1.2838,0.4773,67.2N,145.0E,0,179,NaN,NaN
11894,11895,2999 May 6,23:23:57,4417,12360,154,T,0.8388,1.0566,71.5N,177.3E,33,146,345,03m25s
11895,11896,2999 October 30,09:34:33,4420,12366,159,A-,-1.0023,0.9586,70.9S,84.7W,0,137,-,-
11896,11897,3000 April 26,14:18:06,4424,12372,164,T,0.1310,1.0222,21.1N,18.4W,82,166,76,02m11s
11897,11898,3000 October 19,16:10:16,4428,12378,169,H,-0.2303,1.0049,23.1S,51.6W,77,16,17,00m29s

In [26]:
lunar_df.shape

(11898, 15)

In [41]:
lunar_df.dtypes

Catalog Number         int64
Calendar Date            str
Eclipse Time             str
Delta T (s)            int64
Lunation Number        int64
Saros Number           int64
Eclipse Type             str
Gamma                float64
Eclipse Magnitude    float64
Latitude                 str
Longitude                str
Sun Altitude           int64
Sun Azimuth            int64
Path Width (km)          str
Central Duration         str
dtype: object

In [27]:
lunar_df.describe()

,Catalog Number,Delta T (s),Lunation Number,Saros Number,Gamma,Eclipse Magnitude,Sun Altitude,Sun Azimuth
count,11898.000000,11898.000000,11898.000000,11898.000000,11898.000000,11898.000000,11898.000000,11898.000000
mean,5949.500000,12142.172802,-18546.959321,87.483190,-0.002469,0.812748,36.505295,180.264330
std,3434.801086,13583.402888,17906.572982,48.380284,0.900860,0.300398,32.417350,110.745408
min,1.000000,-6.000000,-49456.000000,-13.000000,-1.569000,0.000000,0.000000,0.000000
25%,2975.250000,970.250000,-33954.750000,47.000000,-0.786575,0.675925,0.000000,89.000000
50%,5949.500000,5636.500000,-18495.000000,87.000000,-0.003850,0.950600,38.000000,180.000000
75%,8923.750000,20943.500000,-3039.250000,128.000000,0.776900,1.018400,66.000000,272.000000
max,11898.000000,46438.000000,12378.000000,190.000000,1.570600,1.081300,90.000000,360.000000

In [29]:
lunar_df.columns

Index(['Catalog Number', 'Calendar Date', 'Eclipse Time', 'Delta T (s)',
       'Lunation Number', 'Saros Number', 'Eclipse Type', 'Gamma',
       'Eclipse Magnitude', 'Latitude', 'Longitude', 'Sun Altitude',
       'Sun Azimuth', 'Path Width (km)', 'Central Duration'],
      dtype='str')

In [30]:
lunar_df.head()

,Catalog Number,Calendar Date,Eclipse Time,Delta T (s),Lunation Number,Saros Number,Eclipse Type,Gamma,Eclipse Magnitude,Latitude,Longitude,Sun Altitude,Sun Azimuth,Path Width (km),Central Duration
0,1,-1999 June 12,03:14:51,46438,-49456,5,T,-0.2701,1.0733,6.0N,33.3W,74,344,247,06m37s
1,2,-1999 December 5,23:45:23,46426,-49450,10,A,-0.2317,0.9382,32.9S,10.8E,76,21,236,06m44s
2,3,-1998 June 1,18:09:16,46415,-49444,15,T,0.4994,1.0284,46.2N,83.4E,60,151,111,02m15s
3,4,-1998 November 25,05:57:03,46403,-49438,20,A,-0.9045,0.9806,67.8S,143.8W,25,74,162,01m14s
4,5,-1997 April 22,13:19:56,46393,-49433,-13,P,-1.4670,0.1611,60.6S,106.4W,0,281,NaN,NaN

In [31]:
lunar_df.isna().sum()

Catalog Number          0
Calendar Date           0
Eclipse Time            0
Delta T (s)             0
Lunation Number         0
Saros Number            0
Eclipse Type            0
Gamma                   0
Eclipse Magnitude       0
Latitude                0
Longitude               0
Sun Altitude            0
Sun Azimuth             0
Path Width (km)      4200
Central Duration     4200
dtype: int64

In [32]:
lunar_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11898 entries, 0 to 11897
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Catalog Number     11898 non-null  int64
 1   Calendar Date      11898 non-null  str
 2   Eclipse Time       11898 non-null  str
 3   Delta T (s)        11898 non-null  int64
 4   Lunation Number    11898 non-null  int64
 5   Saros Number       11898 non-null  int64
 6   Eclipse Type       11898 non-null  str
 7   Gamma              11898 non-null  float64
 8   Eclipse Magnitude  11898 non-null  float64
 9   Latitude           11898 non-null  str
 10  Longitude          11898 non-null  str
 11  Sun Altitude       11898 non-null  int64
 12  Sun Azimuth        11898 non-null  int64
 13  Path Width (km)    7698 non-null   str
 14  Central Duration   7698 non-null   str
dtypes: float64(2), int64(6), str(7)
memory usage: 1.8 MB

In [37]:
lunar_df[lunar_df.duplicated()]

Empty DataFrame
Columns: [Catalog Number, Calendar Date, Eclipse Time, Delta T (s), Lunation Number, Saros Number, Eclipse Type, Gamma, Eclipse Magnitude, Latitude, Longitude, Sun Altitude, Sun Azimuth, Path Width (km), Central Duration]
Index: []